export const initialState = {
  projects: [
    {
      id: 1,
      name: "Website Redesign",
      description: "Обновление дизайна и функциональности веб-сайта компании.",
      startDate: "2024-01-15",
      endDate: "2024-03-30",
      status: "in progress",
      team: ["Иванов", "Петров", "Сидорова"],
      tasks: [
        { id: 1, name: "UI/UX Design", done: true },
        { id: 2, name: "Frontend Development", done: false },
        { id: 3, name: "Backend Development", done: false },
      ],
    },
    {
      id: 2,
      name: "Mobile App Development (Android)",
      description: "Разработка мобильного приложения для платформы Android.",
      startDate: "2023-11-01",
      endDate: "2024-02-28",
      status: "completed",
      team: ["Кузнецов", "Смирнов"],
      tasks: [
        { id: 4, name: "Design Mockups", done: true },
        { id: 5, name: "Native Development", done: true },
        { id: 6, name: "Testing", done: true },
      ],
    },
    {
      id: 3,
      name: "Marketing Campaign",
      description: "Проведение маркетинговой кампании в социальных сетях.",
      startDate: "2024-04-01",
      endDate: "2024-05-15",
      status: "planned",
      team: ["Волкова", "Морозова"],
      tasks: [
        { id: 7, name: "Content Creation", done: false },
        { id: 8, name: "Social Media Promotion", done: false },
      ],
    },
    {
      id: 4,
      name: "iOS App",
      description: "Разработка приложения для iOS.",
      startDate: "2024-02-10",
      endDate: "2024-04-20",
      status: "in progress",
      team: ["Новиков", "Попов"],
      tasks: [
        { id: 25, name: "Push Notifications", done: true },
        { id: 26, name: "Apple Pay Support", done: false },
        { id: 27, name: "UI Design", done: true },
      ],
    },
    {
      id: 5,
      name: "Desktop Application",
      description: "Создание десктопного приложения на C#.",
      startDate: "2023-09-01",
      endDate: "2023-12-31",
      status: "completed",
      team: ["Лебедев"],
      tasks: [
        { id: 28, name: "Core Functionality", done: true },
        { id: 29, name: "UI Development", done: true },
      ],
    },
    {
      id: 6,
      name: "Database Migration",
      description: "Перенос базы данных на новый сервер.",
      startDate: "2024-03-05",
      endDate: "2024-03-10",
      status: "completed",
      team: ["Соколов"],
      tasks: [
        { id: 30, name: "Data Backup", done: true },
        { id: 31, name: "Data Transfer", done: true },
        { id: 32, name: "Verification", done: true },
      ],
    },
    {
      id: 7,
      name: "Internal Tool Development",
      description:
        "Разработка внутреннего инструмента для автоматизации рутинных задач.",
      startDate: "2024-05-01",
      endDate: "2024-07-15",
      status: "planned",
      team: ["Андреев", "Егоров"],
      tasks: [
        { id: 33, name: "Requirements Gathering", done: false },
        { id: 34, name: "Development", done: false },
        { id: 35, name: "Testing", done: false },
      ],
    },
    {
      id: 8,
      name: "Security Audit",
      description: "Проведение аудита безопасности информационной системы.",
      startDate: "2024-06-10",
      endDate: "2024-06-20",
      status: "planned",
      team: ["Козлов"],
      tasks: [
        { id: 36, name: "Vulnerability Scanning", done: false },
        { id: 37, name: "Penetration Testing", done: false },
      ],
    },
    {
      id: 9,
      name: "Training Program",
      description: "Разработка программы обучения для новых сотрудников.",
      startDate: "2024-07-01",
      endDate: "2024-08-30",
      status: "planned",
      team: ["Тихонов", "Николаев"],
      tasks: [
        { id: 38, name: "Curriculum Design", done: false },
        { id: 39, name: "Material Creation", done: false },
      ],
    },
    {
      id: 10,
      name: "Infrastructure Upgrade",
      description: "Модернизация серверной инфраструктуры.",
      startDate: "2024-08-15",
      endDate: "2024-09-30",
      status: "planned",
      team: ["Зайцев"],
      tasks: [
        { id: 40, name: "Hardware Procurement", done: false },
        { id: 41, name: "Installation", done: false },
        { id: 42, name: "Configuration", done: false },
      ],
    },
  ],
};
